import React from 'react';
import { View, Text, TouchableOpacity, StyleSheet, ScrollView } from 'react-native';
import { useRouter } from 'expo-router';

const TERMS = [
  {
    title: '1. Acceptance of Terms',
    content: 'By downloading and using AI Fake News Detector, you agree to these Terms of Service. If you do not agree, please do not use this application.',
  },
  {
    title: '2. Use of the Service',
    content: 'AI Fake News Detector is provided for informational purposes only. The credibility scores and analysis results are generated by AI models and should not be considered as definitive fact-checking. Always verify important news from multiple trusted sources.',
  },
  {
    title: '3. User Accounts',
    content: 'You are responsible for maintaining the confidentiality of your account credentials. You agree not to share your account with others or use the service for any unlawful purpose.',
  },
  {
    title: '4. Content Submission',
    content: 'By submitting articles, URLs, or images for analysis, you confirm that you have the right to submit such content. You agree not to submit content that is illegal, harmful, or violates the rights of others.',
  },
  {
    title: '5. Accuracy Disclaimer',
    content: 'Our AI model achieves 98% accuracy on test data and 75-80% on real-world articles. However, no AI system is perfect. We do not guarantee the accuracy of any analysis result and are not liable for decisions made based on our output.',
  },
  {
    title: '6. Privacy',
    content: 'Your use of this application is also governed by our Privacy Policy. We collect minimal data and do not share your information with third parties. Please review our Privacy Policy for full details.',
  },
  {
    title: '7. Modifications',
    content: 'We reserve the right to modify these terms at any time. Continued use of the application after changes constitutes acceptance of the new terms.',
  },
  {
    title: '8. Contact',
    content: 'If you have any questions about these Terms of Service, please contact us through the Help & Support section of the app.',
  },
];

export default function TermsScreen() {
  const router = useRouter();

  return (
    <ScrollView style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backButton}>
          <Text style={styles.backText}>‹</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Terms of Service</Text>
        <View style={styles.placeholder} />
      </View>

      <View style={styles.content}>
        <View style={styles.heroCard}>
          <Text style={styles.heroIcon}>📄</Text>
          <Text style={styles.heroTitle}>Terms of Service</Text>
          <Text style={styles.heroDate}>Last updated: June 2026</Text>
        </View>

        {TERMS.map((term) => (
          <View key={term.title} style={styles.card}>
            <Text style={styles.cardTitle}>{term.title}</Text>
            <Text style={styles.cardText}>{term.content}</Text>
          </View>
        ))}
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000000' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 24, paddingTop: 60 },
  backButton: { width: 40, height: 40, justifyContent: 'center', alignItems: 'center' },
  backText: { fontSize: 32, color: '#ffffff', fontWeight: '600' },
  headerTitle: { fontSize: 20, fontWeight: '600', color: '#ffffff' },
  placeholder: { width: 40 },
  content: { padding: 24, paddingTop: 8 },
  heroCard: { backgroundColor: '#111111', borderWidth: 1, borderColor: '#333333', borderRadius: 16, padding: 24, alignItems: 'center', marginBottom: 24 },
  heroIcon: { fontSize: 48, marginBottom: 12 },
  heroTitle: { fontSize: 18, fontWeight: '700', color: '#ffffff', marginBottom: 4 },
  heroDate: { fontSize: 13, color: '#888888' },
  card: { backgroundColor: '#111111', borderWidth: 1, borderColor: '#333333', borderRadius: 12, padding: 16, marginBottom: 12 },
  cardTitle: { fontSize: 14, fontWeight: '700', color: '#ffffff', marginBottom: 8 },
  cardText: { fontSize: 13, color: '#888888', lineHeight: 20 },
});