# Generated by Django 5.2.12 on 2026-03-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newssubmission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssubmission',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newssubmission',
            name='suspicious_words',
            field=models.TextField(blank=True, null=True),
        ),
    ]
