# Generated by Django 5.2.12 on 2026-03-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newssubmission_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssubmission',
            name='final_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
