# Generated by Django 5.2.12 on 2026-03-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newssubmission_final_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssubmission',
            name='manipulated_regions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
